
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Sep 08 13:32:35 CEST 2020
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PODELJENOJEDN = 34;
  public static final int PLUSPLUS = 26;
  public static final int ZATZGRD = 17;
  public static final int OTVVITZGRD = 7;
  public static final int JEDNJEDN = 35;
  public static final int ZATVITZGRD = 8;
  public static final int CONST = 29;
  public static final int NUMCONST = 2;
  public static final int CONTINUE = 40;
  public static final int TAR = 52;
  public static final int OTVUGLZGRD = 11;
  public static final int MINUSJEDN = 37;
  public static final int FOR = 49;
  public static final int MINUS = 30;
  public static final int OTVZGRD = 16;
  public static final int ZATUGLZGRD = 14;
  public static final int RAZLICITO = 23;
  public static final int PODELJENO = 12;
  public static final int CLASS = 43;
  public static final int JEDN = 10;
  public static final int II = 50;
  public static final int PUTAJEDN = 32;
  public static final int PLUS = 31;
  public static final int IF = 46;
  public static final int ABSTRACT = 41;
  public static final int EOF = 0;
  public static final int RETURN = 42;
  public static final int MINUSMINUS = 27;
  public static final int ZAP = 18;
  public static final int NEW = 28;
  public static final int error = 1;
  public static final int POSTOJEDN = 33;
  public static final int BREAK = 44;
  public static final int IDENT = 3;
  public static final int VOID = 15;
  public static final int POSTO = 13;
  public static final int MANJE = 39;
  public static final int ELSE = 47;
  public static final int VECE = 21;
  public static final int READ = 25;
  public static final int CHARCONST = 4;
  public static final int MANJEJEDN = 38;
  public static final int TACKA = 22;
  public static final int EXTENDS = 48;
  public static final int BOOLCONST = 5;
  public static final int PROG = 6;
  public static final int ILIILI = 36;
  public static final int AT = 51;
  public static final int PUTA = 19;
  public static final int PLUSJEDN = 45;
  public static final int TACKAZAP = 9;
  public static final int VECEJEDN = 20;
  public static final int PRINT = 24;
}

